### ISSUE TITLE
Dense and filter pipes generate a lot of paths

### ISSUE THREAD

**Issue by redstoneguy12** [cakewhip/ezpas#7]
Steps to reproduce:
1. Build this
![The system that causes the issue](https://user-images.githubusercontent.com/47956142/89832526-7881b880-db2d-11ea-8274-9a5a65ec02c8.png)
2. Click on the puller with a pipe probe

Not only does this make it annoying to diagnose your system, it probably causes lag too

**Comment by redstoneguy12** [comment]
I can confirm that it causes a lot of lag, it brings my server to 10 TPS whenever I update my network with one of those arrays in it (with 6 filters, each connected to two chests). It does not seem to cause too much lag when I push items through the system, however.

**Comment by cakewhip** [comment]
I agree that too many paths are being generated; I'll most likely have the system always take the lowest priority pathing. But yes, because EZPaS pre-calculates insertion points, the only lag you'll mostly experience is from changing any part of the system. To avoid this, you could disconnect any puller pipes and make changes.

On a side note, that system would not behave similar to other pipe mod systems. The right-most chest would have all three filters placed on it. This is an intended effect as items are treated similar to a liquid going through pipes.

**Comment by redstoneguy12** [comment]
> On a side note, that system would not behave similar to other pipe mod systems. The right-most chest would have all three filters placed on it. This is an intended effect as items are treated similar to a liquid going through pipes.

So the filter above that chest has a grass block in it. The hope is that this would behave like a traditional bulk storage unit and only grass blocks would be able to go into that chest, but I didn't actually test it. Are you saying that's not the case, and that grass blocks couldn't go into it?

**Comment by cakewhip** [comment]
No, I mean that items going into the last chest would have to go through every filter. So if the first filter had X block in it and the last filter had Y block in it, Y block would not be able to enter the chest since it does not past the first filter.

**Comment by redstoneguy12** [comment]
But that's what the dense pipes are for, they can't just go through the dense pipes?

**Comment by cakewhip** [comment]
The dense pipes are doing their job, but if you look at the filtered pipes they are connected to each other. Items will take the path of least resistance.

This conversation is getting a bit out of scope, so I will close this.
